python train.py breast_cancer gaussian 0.25 --output_path ./models/ablation_noise_magnitude/breast_cancer_l2 --model_name stump_ensemble_0.25.pkl; \
python certify.py breast_cancer ./models/ablation_noise_magnitude/breast_cancer_l2/stump_ensemble_0.25.pkl ./experiments/ablation_noise_magnitude/breast_cancer_l2 certified_radii_0.25 gaussian 0.25 --device cuda; \
python train.py breast_cancer gaussian 0.5 --output_path ./models/ablation_noise_magnitude/breast_cancer_l2 --model_name stump_ensemble_0.5.pkl; \
python certify.py breast_cancer ./models/ablation_noise_magnitude/breast_cancer_l2/stump_ensemble_0.5.pkl ./experiments/ablation_noise_magnitude/breast_cancer_l2 certified_radii_0.5 gaussian 0.5 --device cuda; \
python train.py breast_cancer gaussian 1.0 --output_path ./models/ablation_noise_magnitude/breast_cancer_l2 --model_name stump_ensemble_1.0.pkl; \
python certify.py breast_cancer ./models/ablation_noise_magnitude/breast_cancer_l2/stump_ensemble_1.0.pkl ./experiments/ablation_noise_magnitude/breast_cancer_l2 certified_radii_1.0 gaussian 1.0 --device cuda; \
python train.py breast_cancer gaussian 2.0 --output_path ./models/ablation_noise_magnitude/breast_cancer_l2 --model_name stump_ensemble_2.0.pkl; \
python certify.py breast_cancer ./models/ablation_noise_magnitude/breast_cancer_l2/stump_ensemble_2.0.pkl ./experiments/ablation_noise_magnitude/breast_cancer_l2 certified_radii_2.0 gaussian 2.0 --device cuda; \
python train.py breast_cancer gaussian 4.0 --output_path ./models/ablation_noise_magnitude/breast_cancer_l2 --model_name stump_ensemble_4.0.pkl; \
python certify.py breast_cancer ./models/ablation_noise_magnitude/breast_cancer_l2/stump_ensemble_4.0.pkl ./experiments/ablation_noise_magnitude/breast_cancer_l2 certified_radii_4.0 gaussian 4.0 --device cuda; \
python train.py breast_cancer gaussian 8.0 --output_path ./models/ablation_noise_magnitude/breast_cancer_l2 --model_name stump_ensemble_8.0.pkl; \
python certify.py breast_cancer ./models/ablation_noise_magnitude/breast_cancer_l2/stump_ensemble_8.0.pkl ./experiments/ablation_noise_magnitude/breast_cancer_l2 certified_radii_8.0 gaussian 8.0 --device cuda; \
python analyze.py ./experiments/ablation_noise_magnitude/breast_cancer_l2/table 2 ./experiments/ablation_noise_magnitude/breast_cancer_l2/certified_radii_0.25 ./experiments/ablation_noise_magnitude/breast_cancer_l2/certified_radii_0.5 ./experiments/ablation_noise_magnitude/breast_cancer_l2/certified_radii_1.0 ./experiments/ablation_noise_magnitude/breast_cancer_l2/certified_radii_2.0 ./experiments/ablation_noise_magnitude/breast_cancer_l2/certified_radii_4.0 ./experiments/ablation_noise_magnitude/breast_cancer_l2/certified_radii_8.0; \
python train.py diabetes gaussian 0.25 --output_path ./models/ablation_noise_magnitude/diabetes_l2 --model_name stump_ensemble_0.25.pkl; \
python certify.py diabetes ./models/ablation_noise_magnitude/diabetes_l2/stump_ensemble_0.25.pkl ./experiments/ablation_noise_magnitude/diabetes_l2 certified_radii_0.25 gaussian 0.25 --device cuda; \
python train.py diabetes gaussian 0.5 --output_path ./models/ablation_noise_magnitude/diabetes_l2 --model_name stump_ensemble_0.5.pkl; \
python certify.py diabetes ./models/ablation_noise_magnitude/diabetes_l2/stump_ensemble_0.5.pkl ./experiments/ablation_noise_magnitude/diabetes_l2 certified_radii_0.5 gaussian 0.5 --device cuda; \
python train.py diabetes gaussian 1.0 --output_path ./models/ablation_noise_magnitude/diabetes_l2 --model_name stump_ensemble_1.0.pkl; \
python certify.py diabetes ./models/ablation_noise_magnitude/diabetes_l2/stump_ensemble_1.0.pkl ./experiments/ablation_noise_magnitude/diabetes_l2 certified_radii_1.0 gaussian 1.0 --device cuda; \
python train.py diabetes gaussian 2.0 --output_path ./models/ablation_noise_magnitude/diabetes_l2 --model_name stump_ensemble_2.0.pkl; \
python certify.py diabetes ./models/ablation_noise_magnitude/diabetes_l2/stump_ensemble_2.0.pkl ./experiments/ablation_noise_magnitude/diabetes_l2 certified_radii_2.0 gaussian 2.0 --device cuda; \
python train.py diabetes gaussian 4.0 --output_path ./models/ablation_noise_magnitude/diabetes_l2 --model_name stump_ensemble_4.0.pkl; \
python certify.py diabetes ./models/ablation_noise_magnitude/diabetes_l2/stump_ensemble_4.0.pkl ./experiments/ablation_noise_magnitude/diabetes_l2 certified_radii_4.0 gaussian 4.0 --device cuda; \
python train.py diabetes gaussian 8.0 --output_path ./models/ablation_noise_magnitude/diabetes_l2 --model_name stump_ensemble_8.0.pkl; \
python certify.py diabetes ./models/ablation_noise_magnitude/diabetes_l2/stump_ensemble_8.0.pkl ./experiments/ablation_noise_magnitude/diabetes_l2 certified_radii_8.0 gaussian 8.0 --device cuda; \
python analyze.py ./experiments/ablation_noise_magnitude/diabetes_l2/table 2 ./experiments/ablation_noise_magnitude/diabetes_l2/certified_radii_0.25 ./experiments/ablation_noise_magnitude/diabetes_l2/certified_radii_0.5 ./experiments/ablation_noise_magnitude/diabetes_l2/certified_radii_1.0 ./experiments/ablation_noise_magnitude/diabetes_l2/certified_radii_2.0 ./experiments/ablation_noise_magnitude/diabetes_l2/certified_radii_4.0 ./experiments/ablation_noise_magnitude/diabetes_l2/certified_radii_8.0; \
python train.py fmnist_sandal_sneaker gaussian 0.25 --output_path ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l2 --model_name stump_ensemble_0.25.pkl; \
python certify.py fmnist_sandal_sneaker ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l2/stump_ensemble_0.25.pkl ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l2 certified_radii_0.25 gaussian 0.25 --device cuda; \
python train.py fmnist_sandal_sneaker gaussian 0.5 --output_path ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l2 --model_name stump_ensemble_0.5.pkl; \
python certify.py fmnist_sandal_sneaker ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l2/stump_ensemble_0.5.pkl ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l2 certified_radii_0.5 gaussian 0.5 --device cuda; \
python train.py fmnist_sandal_sneaker gaussian 1.0 --output_path ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l2 --model_name stump_ensemble_1.0.pkl; \
python certify.py fmnist_sandal_sneaker ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l2/stump_ensemble_1.0.pkl ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l2 certified_radii_1.0 gaussian 1.0 --device cuda; \
python train.py fmnist_sandal_sneaker gaussian 2.0 --output_path ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l2 --model_name stump_ensemble_2.0.pkl; \
python certify.py fmnist_sandal_sneaker ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l2/stump_ensemble_2.0.pkl ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l2 certified_radii_2.0 gaussian 2.0 --device cuda; \
python train.py fmnist_sandal_sneaker gaussian 4.0 --output_path ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l2 --model_name stump_ensemble_4.0.pkl; \
python certify.py fmnist_sandal_sneaker ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l2/stump_ensemble_4.0.pkl ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l2 certified_radii_4.0 gaussian 4.0 --device cuda; \
python train.py fmnist_sandal_sneaker gaussian 8.0 --output_path ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l2 --model_name stump_ensemble_8.0.pkl; \
python certify.py fmnist_sandal_sneaker ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l2/stump_ensemble_8.0.pkl ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l2 certified_radii_8.0 gaussian 8.0 --device cuda; \
python analyze.py ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l2/table 2 ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l2/certified_radii_0.25 ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l2/certified_radii_0.5 ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l2/certified_radii_1.0 ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l2/certified_radii_2.0 ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l2/certified_radii_4.0 ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l2/certified_radii_8.0; \
python train.py mnist_1_5 gaussian 0.25 --output_path ./models/ablation_noise_magnitude/mnist_1_5_l2 --model_name stump_ensemble_0.25.pkl; \
python certify.py mnist_1_5 ./models/ablation_noise_magnitude/mnist_1_5_l2/stump_ensemble_0.25.pkl ./experiments/ablation_noise_magnitude/mnist_1_5_l2 certified_radii_0.25 gaussian 0.25 --device cuda; \
python train.py mnist_1_5 gaussian 0.5 --output_path ./models/ablation_noise_magnitude/mnist_1_5_l2 --model_name stump_ensemble_0.5.pkl; \
python certify.py mnist_1_5 ./models/ablation_noise_magnitude/mnist_1_5_l2/stump_ensemble_0.5.pkl ./experiments/ablation_noise_magnitude/mnist_1_5_l2 certified_radii_0.5 gaussian 0.5 --device cuda; \
python train.py mnist_1_5 gaussian 1.0 --output_path ./models/ablation_noise_magnitude/mnist_1_5_l2 --model_name stump_ensemble_1.0.pkl; \
python certify.py mnist_1_5 ./models/ablation_noise_magnitude/mnist_1_5_l2/stump_ensemble_1.0.pkl ./experiments/ablation_noise_magnitude/mnist_1_5_l2 certified_radii_1.0 gaussian 1.0 --device cuda; \
python train.py mnist_1_5 gaussian 2.0 --output_path ./models/ablation_noise_magnitude/mnist_1_5_l2 --model_name stump_ensemble_2.0.pkl; \
python certify.py mnist_1_5 ./models/ablation_noise_magnitude/mnist_1_5_l2/stump_ensemble_2.0.pkl ./experiments/ablation_noise_magnitude/mnist_1_5_l2 certified_radii_2.0 gaussian 2.0 --device cuda; \
python train.py mnist_1_5 gaussian 4.0 --output_path ./models/ablation_noise_magnitude/mnist_1_5_l2 --model_name stump_ensemble_4.0.pkl; \
python certify.py mnist_1_5 ./models/ablation_noise_magnitude/mnist_1_5_l2/stump_ensemble_4.0.pkl ./experiments/ablation_noise_magnitude/mnist_1_5_l2 certified_radii_4.0 gaussian 4.0 --device cuda; \
python train.py mnist_1_5 gaussian 8.0 --output_path ./models/ablation_noise_magnitude/mnist_1_5_l2 --model_name stump_ensemble_8.0.pkl; \
python certify.py mnist_1_5 ./models/ablation_noise_magnitude/mnist_1_5_l2/stump_ensemble_8.0.pkl ./experiments/ablation_noise_magnitude/mnist_1_5_l2 certified_radii_8.0 gaussian 8.0 --device cuda; \
python analyze.py ./experiments/ablation_noise_magnitude/mnist_1_5_l2/table 2 ./experiments/ablation_noise_magnitude/mnist_1_5_l2/certified_radii_0.25 ./experiments/ablation_noise_magnitude/mnist_1_5_l2/certified_radii_0.5 ./experiments/ablation_noise_magnitude/mnist_1_5_l2/certified_radii_1.0 ./experiments/ablation_noise_magnitude/mnist_1_5_l2/certified_radii_2.0 ./experiments/ablation_noise_magnitude/mnist_1_5_l2/certified_radii_4.0 ./experiments/ablation_noise_magnitude/mnist_1_5_l2/certified_radii_8.0; \
python train.py mnist_2_6 gaussian 0.25 --output_path ./models/ablation_noise_magnitude/mnist_2_6_l2 --model_name stump_ensemble_0.25.pkl; \
python certify.py mnist_2_6 ./models/ablation_noise_magnitude/mnist_2_6_l2/stump_ensemble_0.25.pkl ./experiments/ablation_noise_magnitude/mnist_2_6_l2 certified_radii_0.25 gaussian 0.25 --device cuda; \
python train.py mnist_2_6 gaussian 0.5 --output_path ./models/ablation_noise_magnitude/mnist_2_6_l2 --model_name stump_ensemble_0.5.pkl; \
python certify.py mnist_2_6 ./models/ablation_noise_magnitude/mnist_2_6_l2/stump_ensemble_0.5.pkl ./experiments/ablation_noise_magnitude/mnist_2_6_l2 certified_radii_0.5 gaussian 0.5 --device cuda; \
python train.py mnist_2_6 gaussian 1.0 --output_path ./models/ablation_noise_magnitude/mnist_2_6_l2 --model_name stump_ensemble_1.0.pkl; \
python certify.py mnist_2_6 ./models/ablation_noise_magnitude/mnist_2_6_l2/stump_ensemble_1.0.pkl ./experiments/ablation_noise_magnitude/mnist_2_6_l2 certified_radii_1.0 gaussian 1.0 --device cuda; \
python train.py mnist_2_6 gaussian 2.0 --output_path ./models/ablation_noise_magnitude/mnist_2_6_l2 --model_name stump_ensemble_2.0.pkl; \
python certify.py mnist_2_6 ./models/ablation_noise_magnitude/mnist_2_6_l2/stump_ensemble_2.0.pkl ./experiments/ablation_noise_magnitude/mnist_2_6_l2 certified_radii_2.0 gaussian 2.0 --device cuda; \
python train.py mnist_2_6 gaussian 4.0 --output_path ./models/ablation_noise_magnitude/mnist_2_6_l2 --model_name stump_ensemble_4.0.pkl; \
python certify.py mnist_2_6 ./models/ablation_noise_magnitude/mnist_2_6_l2/stump_ensemble_4.0.pkl ./experiments/ablation_noise_magnitude/mnist_2_6_l2 certified_radii_4.0 gaussian 4.0 --device cuda; \
python train.py mnist_2_6 gaussian 8.0 --output_path ./models/ablation_noise_magnitude/mnist_2_6_l2 --model_name stump_ensemble_8.0.pkl; \
python certify.py mnist_2_6 ./models/ablation_noise_magnitude/mnist_2_6_l2/stump_ensemble_8.0.pkl ./experiments/ablation_noise_magnitude/mnist_2_6_l2 certified_radii_8.0 gaussian 8.0 --device cuda; \
python analyze.py ./experiments/ablation_noise_magnitude/mnist_2_6_l2/table 2 ./experiments/ablation_noise_magnitude/mnist_2_6_l2/certified_radii_0.25 ./experiments/ablation_noise_magnitude/mnist_2_6_l2/certified_radii_0.5 ./experiments/ablation_noise_magnitude/mnist_2_6_l2/certified_radii_1.0 ./experiments/ablation_noise_magnitude/mnist_2_6_l2/certified_radii_2.0 ./experiments/ablation_noise_magnitude/mnist_2_6_l2/certified_radii_4.0 ./experiments/ablation_noise_magnitude/mnist_2_6_l2/certified_radii_8.0;
