python train.py breast_cancer uniform 0.5 --output_path ./models/ablation_noise_magnitude/breast_cancer_l1 --model_name stump_ensemble_0.5.pkl; \
python certify.py breast_cancer ./models/ablation_noise_magnitude/breast_cancer_l1/stump_ensemble_0.5.pkl ./experiments/ablation_noise_magnitude/breast_cancer_l1 certified_radii_0.5 uniform 0.5 --device cuda; \
python train.py breast_cancer uniform 1.0 --output_path ./models/ablation_noise_magnitude/breast_cancer_l1 --model_name stump_ensemble_1.0.pkl; \
python certify.py breast_cancer ./models/ablation_noise_magnitude/breast_cancer_l1/stump_ensemble_1.0.pkl ./experiments/ablation_noise_magnitude/breast_cancer_l1 certified_radii_1.0 uniform 1.0 --device cuda; \
python train.py breast_cancer uniform 2.0 --output_path ./models/ablation_noise_magnitude/breast_cancer_l1 --model_name stump_ensemble_2.0.pkl; \
python certify.py breast_cancer ./models/ablation_noise_magnitude/breast_cancer_l1/stump_ensemble_2.0.pkl ./experiments/ablation_noise_magnitude/breast_cancer_l1 certified_radii_2.0 uniform 2.0 --device cuda; \
python train.py breast_cancer uniform 4.0 --output_path ./models/ablation_noise_magnitude/breast_cancer_l1 --model_name stump_ensemble_4.0.pkl; \
python certify.py breast_cancer ./models/ablation_noise_magnitude/breast_cancer_l1/stump_ensemble_4.0.pkl ./experiments/ablation_noise_magnitude/breast_cancer_l1 certified_radii_4.0 uniform 4.0 --device cuda; \
python train.py breast_cancer uniform 8.0 --output_path ./models/ablation_noise_magnitude/breast_cancer_l1 --model_name stump_ensemble_8.0.pkl; \
python certify.py breast_cancer ./models/ablation_noise_magnitude/breast_cancer_l1/stump_ensemble_8.0.pkl ./experiments/ablation_noise_magnitude/breast_cancer_l1 certified_radii_8.0 uniform 8.0 --device cuda; \
python train.py breast_cancer uniform 16.0 --output_path ./models/ablation_noise_magnitude/breast_cancer_l1 --model_name stump_ensemble_16.0.pkl; \
python certify.py breast_cancer ./models/ablation_noise_magnitude/breast_cancer_l1/stump_ensemble_16.0.pkl ./experiments/ablation_noise_magnitude/breast_cancer_l1 certified_radii_16.0 uniform 16.0 --device cuda; \
python analyze.py ./experiments/ablation_noise_magnitude/breast_cancer_l1/table 3 ./experiments/ablation_noise_magnitude/breast_cancer_l1/certified_radii_0.5 ./experiments/ablation_noise_magnitude/breast_cancer_l1/certified_radii_1.0 ./experiments/ablation_noise_magnitude/breast_cancer_l1/certified_radii_2.0 ./experiments/ablation_noise_magnitude/breast_cancer_l1/certified_radii_4.0 ./experiments/ablation_noise_magnitude/breast_cancer_l1/certified_radii_8.0 ./experiments/ablation_noise_magnitude/breast_cancer_l1/certified_radii_16.0; \
python train.py diabetes uniform 0.5 --output_path ./models/ablation_noise_magnitude/diabetes_l1 --model_name stump_ensemble_0.5.pkl; \
python certify.py diabetes ./models/ablation_noise_magnitude/diabetes_l1/stump_ensemble_0.5.pkl ./experiments/ablation_noise_magnitude/diabetes_l1 certified_radii_0.5 uniform 0.5 --device cuda; \
python train.py diabetes uniform 1.0 --output_path ./models/ablation_noise_magnitude/diabetes_l1 --model_name stump_ensemble_1.0.pkl; \
python certify.py diabetes ./models/ablation_noise_magnitude/diabetes_l1/stump_ensemble_1.0.pkl ./experiments/ablation_noise_magnitude/diabetes_l1 certified_radii_1.0 uniform 1.0 --device cuda; \
python train.py diabetes uniform 2.0 --output_path ./models/ablation_noise_magnitude/diabetes_l1 --model_name stump_ensemble_2.0.pkl; \
python certify.py diabetes ./models/ablation_noise_magnitude/diabetes_l1/stump_ensemble_2.0.pkl ./experiments/ablation_noise_magnitude/diabetes_l1 certified_radii_2.0 uniform 2.0 --device cuda; \
python train.py diabetes uniform 4.0 --output_path ./models/ablation_noise_magnitude/diabetes_l1 --model_name stump_ensemble_4.0.pkl; \
python certify.py diabetes ./models/ablation_noise_magnitude/diabetes_l1/stump_ensemble_4.0.pkl ./experiments/ablation_noise_magnitude/diabetes_l1 certified_radii_4.0 uniform 4.0 --device cuda; \
python train.py diabetes uniform 8.0 --output_path ./models/ablation_noise_magnitude/diabetes_l1 --model_name stump_ensemble_8.0.pkl; \
python certify.py diabetes ./models/ablation_noise_magnitude/diabetes_l1/stump_ensemble_8.0.pkl ./experiments/ablation_noise_magnitude/diabetes_l1 certified_radii_8.0 uniform 8.0 --device cuda; \
python train.py diabetes uniform 16.0 --output_path ./models/ablation_noise_magnitude/diabetes_l1 --model_name stump_ensemble_16.0.pkl; \
python certify.py diabetes ./models/ablation_noise_magnitude/diabetes_l1/stump_ensemble_16.0.pkl ./experiments/ablation_noise_magnitude/diabetes_l1 certified_radii_16.0 uniform 16.0 --device cuda; \
python analyze.py ./experiments/ablation_noise_magnitude/diabetes_l1/table 3 ./experiments/ablation_noise_magnitude/diabetes_l1/certified_radii_0.5 ./experiments/ablation_noise_magnitude/diabetes_l1/certified_radii_1.0 ./experiments/ablation_noise_magnitude/diabetes_l1/certified_radii_2.0 ./experiments/ablation_noise_magnitude/diabetes_l1/certified_radii_4.0 ./experiments/ablation_noise_magnitude/diabetes_l1/certified_radii_8.0 ./experiments/ablation_noise_magnitude/diabetes_l1/certified_radii_16.0; \
python train.py fmnist_sandal_sneaker uniform 0.5 --output_path ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l1 --model_name stump_ensemble_0.5.pkl; \
python certify.py fmnist_sandal_sneaker ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l1/stump_ensemble_0.5.pkl ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l1 certified_radii_0.5 uniform 0.5 --device cuda; \
python train.py fmnist_sandal_sneaker uniform 1.0 --output_path ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l1 --model_name stump_ensemble_1.0.pkl; \
python certify.py fmnist_sandal_sneaker ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l1/stump_ensemble_1.0.pkl ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l1 certified_radii_1.0 uniform 1.0 --device cuda; \
python train.py fmnist_sandal_sneaker uniform 2.0 --output_path ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l1 --model_name stump_ensemble_2.0.pkl; \
python certify.py fmnist_sandal_sneaker ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l1/stump_ensemble_2.0.pkl ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l1 certified_radii_2.0 uniform 2.0 --device cuda; \
python train.py fmnist_sandal_sneaker uniform 4.0 --output_path ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l1 --model_name stump_ensemble_4.0.pkl; \
python certify.py fmnist_sandal_sneaker ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l1/stump_ensemble_4.0.pkl ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l1 certified_radii_4.0 uniform 4.0 --device cuda; \
python train.py fmnist_sandal_sneaker uniform 8.0 --output_path ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l1 --model_name stump_ensemble_8.0.pkl; \
python certify.py fmnist_sandal_sneaker ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l1/stump_ensemble_8.0.pkl ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l1 certified_radii_8.0 uniform 8.0 --device cuda; \
python train.py fmnist_sandal_sneaker uniform 16.0 --output_path ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l1 --model_name stump_ensemble_16.0.pkl; \
python certify.py fmnist_sandal_sneaker ./models/ablation_noise_magnitude/fmnist_sandal_sneaker_l1/stump_ensemble_16.0.pkl ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l1 certified_radii_16.0 uniform 16.0 --device cuda; \
python analyze.py ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l1/table 3 ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l1/certified_radii_0.5 ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l1/certified_radii_1.0 ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l1/certified_radii_2.0 ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l1/certified_radii_4.0 ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l1/certified_radii_8.0 ./experiments/ablation_noise_magnitude/fmnist_sandal_sneaker_l1/certified_radii_16.0; \
python train.py mnist_1_5 uniform 0.5 --output_path ./models/ablation_noise_magnitude/mnist_1_5_l1 --model_name stump_ensemble_0.5.pkl; \
python certify.py mnist_1_5 ./models/ablation_noise_magnitude/mnist_1_5_l1/stump_ensemble_0.5.pkl ./experiments/ablation_noise_magnitude/mnist_1_5_l1 certified_radii_0.5 uniform 0.5 --device cuda; \
python train.py mnist_1_5 uniform 1.0 --output_path ./models/ablation_noise_magnitude/mnist_1_5_l1 --model_name stump_ensemble_1.0.pkl; \
python certify.py mnist_1_5 ./models/ablation_noise_magnitude/mnist_1_5_l1/stump_ensemble_1.0.pkl ./experiments/ablation_noise_magnitude/mnist_1_5_l1 certified_radii_1.0 uniform 1.0 --device cuda; \
python train.py mnist_1_5 uniform 2.0 --output_path ./models/ablation_noise_magnitude/mnist_1_5_l1 --model_name stump_ensemble_2.0.pkl; \
python certify.py mnist_1_5 ./models/ablation_noise_magnitude/mnist_1_5_l1/stump_ensemble_2.0.pkl ./experiments/ablation_noise_magnitude/mnist_1_5_l1 certified_radii_2.0 uniform 2.0 --device cuda; \
python train.py mnist_1_5 uniform 4.0 --output_path ./models/ablation_noise_magnitude/mnist_1_5_l1 --model_name stump_ensemble_4.0.pkl; \
python certify.py mnist_1_5 ./models/ablation_noise_magnitude/mnist_1_5_l1/stump_ensemble_4.0.pkl ./experiments/ablation_noise_magnitude/mnist_1_5_l1 certified_radii_4.0 uniform 4.0 --device cuda; \
python train.py mnist_1_5 uniform 8.0 --output_path ./models/ablation_noise_magnitude/mnist_1_5_l1 --model_name stump_ensemble_8.0.pkl; \
python certify.py mnist_1_5 ./models/ablation_noise_magnitude/mnist_1_5_l1/stump_ensemble_8.0.pkl ./experiments/ablation_noise_magnitude/mnist_1_5_l1 certified_radii_8.0 uniform 8.0 --device cuda; \
python train.py mnist_1_5 uniform 16.0 --output_path ./models/ablation_noise_magnitude/mnist_1_5_l1 --model_name stump_ensemble_16.0.pkl; \
python certify.py mnist_1_5 ./models/ablation_noise_magnitude/mnist_1_5_l1/stump_ensemble_16.0.pkl ./experiments/ablation_noise_magnitude/mnist_1_5_l1 certified_radii_16.0 uniform 16.0 --device cuda; \
python analyze.py ./experiments/ablation_noise_magnitude/mnist_1_5_l1/table 3 ./experiments/ablation_noise_magnitude/mnist_1_5_l1/certified_radii_0.5 ./experiments/ablation_noise_magnitude/mnist_1_5_l1/certified_radii_1.0 ./experiments/ablation_noise_magnitude/mnist_1_5_l1/certified_radii_2.0 ./experiments/ablation_noise_magnitude/mnist_1_5_l1/certified_radii_4.0 ./experiments/ablation_noise_magnitude/mnist_1_5_l1/certified_radii_8.0 ./experiments/ablation_noise_magnitude/mnist_1_5_l1/certified_radii_16.0; \
python train.py mnist_2_6 uniform 0.5 --output_path ./models/ablation_noise_magnitude/mnist_2_6_l1 --model_name stump_ensemble_0.5.pkl; \
python certify.py mnist_2_6 ./models/ablation_noise_magnitude/mnist_2_6_l1/stump_ensemble_0.5.pkl ./experiments/ablation_noise_magnitude/mnist_2_6_l1 certified_radii_0.5 uniform 0.5 --device cuda; \
python train.py mnist_2_6 uniform 1.0 --output_path ./models/ablation_noise_magnitude/mnist_2_6_l1 --model_name stump_ensemble_1.0.pkl; \
python certify.py mnist_2_6 ./models/ablation_noise_magnitude/mnist_2_6_l1/stump_ensemble_1.0.pkl ./experiments/ablation_noise_magnitude/mnist_2_6_l1 certified_radii_1.0 uniform 1.0 --device cuda; \
python train.py mnist_2_6 uniform 2.0 --output_path ./models/ablation_noise_magnitude/mnist_2_6_l1 --model_name stump_ensemble_2.0.pkl; \
python certify.py mnist_2_6 ./models/ablation_noise_magnitude/mnist_2_6_l1/stump_ensemble_2.0.pkl ./experiments/ablation_noise_magnitude/mnist_2_6_l1 certified_radii_2.0 uniform 2.0 --device cuda; \
python train.py mnist_2_6 uniform 4.0 --output_path ./models/ablation_noise_magnitude/mnist_2_6_l1 --model_name stump_ensemble_4.0.pkl; \
python certify.py mnist_2_6 ./models/ablation_noise_magnitude/mnist_2_6_l1/stump_ensemble_4.0.pkl ./experiments/ablation_noise_magnitude/mnist_2_6_l1 certified_radii_4.0 uniform 4.0 --device cuda; \
python train.py mnist_2_6 uniform 8.0 --output_path ./models/ablation_noise_magnitude/mnist_2_6_l1 --model_name stump_ensemble_8.0.pkl; \
python certify.py mnist_2_6 ./models/ablation_noise_magnitude/mnist_2_6_l1/stump_ensemble_8.0.pkl ./experiments/ablation_noise_magnitude/mnist_2_6_l1 certified_radii_8.0 uniform 8.0 --device cuda; \
python train.py mnist_2_6 uniform 16.0 --output_path ./models/ablation_noise_magnitude/mnist_2_6_l1 --model_name stump_ensemble_16.0.pkl; \
python certify.py mnist_2_6 ./models/ablation_noise_magnitude/mnist_2_6_l1/stump_ensemble_16.0.pkl ./experiments/ablation_noise_magnitude/mnist_2_6_l1 certified_radii_16.0 uniform 16.0 --device cuda; \
python analyze.py ./experiments/ablation_noise_magnitude/mnist_2_6_l1/table 3 ./experiments/ablation_noise_magnitude/mnist_2_6_l1/certified_radii_0.5 ./experiments/ablation_noise_magnitude/mnist_2_6_l1/certified_radii_1.0 ./experiments/ablation_noise_magnitude/mnist_2_6_l1/certified_radii_2.0 ./experiments/ablation_noise_magnitude/mnist_2_6_l1/certified_radii_4.0 ./experiments/ablation_noise_magnitude/mnist_2_6_l1/certified_radii_8.0 ./experiments/ablation_noise_magnitude/mnist_2_6_l1/certified_radii_16.0;
