python train.py mnist_1_5 uniform 4.0 --output_path ./models/discretizations_cv/mnist_1_5_l1_1000_0 --model_name stump_ensemble.pkl --current_fold 0 --n_splits 5 --discretization 1000; \
python certify.py mnist_1_5 ./models/discretizations_cv/mnist_1_5_l1_1000_0/stump_ensemble.pkl ./experiments/discretizations_cv//mnist_1_5_l1_1000_0 certified_radii uniform 4.0 --device cuda --current_fold 0 --n_splits 5; \
python train.py mnist_1_5 uniform 4.0 --output_path ./models/discretizations_cv/mnist_1_5_l1_1000_1 --model_name stump_ensemble.pkl --current_fold 1 --n_splits 5 --discretization 1000; \
python certify.py mnist_1_5 ./models/discretizations_cv/mnist_1_5_l1_1000_1/stump_ensemble.pkl ./experiments/discretizations_cv//mnist_1_5_l1_1000_1 certified_radii uniform 4.0 --device cuda --current_fold 1 --n_splits 5; \
python train.py mnist_1_5 uniform 4.0 --output_path ./models/discretizations_cv/mnist_1_5_l1_1000_2 --model_name stump_ensemble.pkl --current_fold 2 --n_splits 5 --discretization 1000; \
python certify.py mnist_1_5 ./models/discretizations_cv/mnist_1_5_l1_1000_2/stump_ensemble.pkl ./experiments/discretizations_cv//mnist_1_5_l1_1000_2 certified_radii uniform 4.0 --device cuda --current_fold 2 --n_splits 5; \
python train.py mnist_1_5 uniform 4.0 --output_path ./models/discretizations_cv/mnist_1_5_l1_1000_3 --model_name stump_ensemble.pkl --current_fold 3 --n_splits 5 --discretization 1000; \
python certify.py mnist_1_5 ./models/discretizations_cv/mnist_1_5_l1_1000_3/stump_ensemble.pkl ./experiments/discretizations_cv//mnist_1_5_l1_1000_3 certified_radii uniform 4.0 --device cuda --current_fold 3 --n_splits 5; \
python train.py mnist_1_5 uniform 4.0 --output_path ./models/discretizations_cv/mnist_1_5_l1_1000_4 --model_name stump_ensemble.pkl --current_fold 4 --n_splits 5 --discretization 1000; \
python certify.py mnist_1_5 ./models/discretizations_cv/mnist_1_5_l1_1000_4/stump_ensemble.pkl ./experiments/discretizations_cv//mnist_1_5_l1_1000_4 certified_radii uniform 4.0 --device cuda --current_fold 4 --n_splits 5; \
python analyze.py ./experiments/discretizations_cv/mnist_1_5_l1_1000/table 2 ./experiments/discretizations_cv/mnist_1_5_l1_1000_0/certified_radii ./experiments/discretizations_cv/mnist_1_5_l1_1000_1/certified_radii ./experiments/discretizations_cv/mnist_1_5_l1_1000_2/certified_radii ./experiments/discretizations_cv/mnist_1_5_l1_1000_3/certified_radii ./experiments/discretizations_cv/mnist_1_5_l1_1000_4/certified_radii; \
