python train.py breast_cancer uniform 2.0 --output_path ./models/independent_cv/breast_cancer_l1_0 --model_name stump_ensemble.pkl --current_fold 0 --n_splits 5; \
python certify.py breast_cancer ./models/independent_cv/breast_cancer_l1_0/stump_ensemble.pkl ./experiments/independent_cv//breast_cancer_l1_0 certified_radii uniform 2.0 --device cuda --current_fold 0 --n_splits 5; \
python train.py breast_cancer uniform 2.0 --output_path ./models/independent_cv/breast_cancer_l1_1 --model_name stump_ensemble.pkl --current_fold 1 --n_splits 5; \
python certify.py breast_cancer ./models/independent_cv/breast_cancer_l1_1/stump_ensemble.pkl ./experiments/independent_cv//breast_cancer_l1_1 certified_radii uniform 2.0 --device cuda --current_fold 1 --n_splits 5; \
python train.py breast_cancer uniform 2.0 --output_path ./models/independent_cv/breast_cancer_l1_2 --model_name stump_ensemble.pkl --current_fold 2 --n_splits 5; \
python certify.py breast_cancer ./models/independent_cv/breast_cancer_l1_2/stump_ensemble.pkl ./experiments/independent_cv//breast_cancer_l1_2 certified_radii uniform 2.0 --device cuda --current_fold 2 --n_splits 5; \
python train.py breast_cancer uniform 2.0 --output_path ./models/independent_cv/breast_cancer_l1_3 --model_name stump_ensemble.pkl --current_fold 3 --n_splits 5; \
python certify.py breast_cancer ./models/independent_cv/breast_cancer_l1_3/stump_ensemble.pkl ./experiments/independent_cv//breast_cancer_l1_3 certified_radii uniform 2.0 --device cuda --current_fold 3 --n_splits 5; \
python train.py breast_cancer uniform 2.0 --output_path ./models/independent_cv/breast_cancer_l1_4 --model_name stump_ensemble.pkl --current_fold 4 --n_splits 5; \
python certify.py breast_cancer ./models/independent_cv/breast_cancer_l1_4/stump_ensemble.pkl ./experiments/independent_cv//breast_cancer_l1_4 certified_radii uniform 2.0 --device cuda --current_fold 4 --n_splits 5; \
python analyze.py ./experiments/independent_cv/breast_cancer_l1/table 5 ./experiments/independent_cv/breast_cancer_l1_0/certified_radii ./experiments/independent_cv/breast_cancer_l1_1/certified_radii ./experiments/independent_cv/breast_cancer_l1_2/certified_radii ./experiments/independent_cv/breast_cancer_l1_3/certified_radii ./experiments/independent_cv/breast_cancer_l1_4/certified_radii; \
python train.py diabetes uniform 0.35 --output_path ./models/independent_cv/diabetes_l1_0 --model_name stump_ensemble.pkl --current_fold 0 --n_splits 5; \
python certify.py diabetes ./models/independent_cv/diabetes_l1_0/stump_ensemble.pkl ./experiments/independent_cv//diabetes_l1_0 certified_radii uniform 0.35 --device cuda --current_fold 0 --n_splits 5; \
python train.py diabetes uniform 0.35 --output_path ./models/independent_cv/diabetes_l1_1 --model_name stump_ensemble.pkl --current_fold 1 --n_splits 5; \
python certify.py diabetes ./models/independent_cv/diabetes_l1_1/stump_ensemble.pkl ./experiments/independent_cv//diabetes_l1_1 certified_radii uniform 0.35 --device cuda --current_fold 1 --n_splits 5; \
python train.py diabetes uniform 0.35 --output_path ./models/independent_cv/diabetes_l1_2 --model_name stump_ensemble.pkl --current_fold 2 --n_splits 5; \
python certify.py diabetes ./models/independent_cv/diabetes_l1_2/stump_ensemble.pkl ./experiments/independent_cv//diabetes_l1_2 certified_radii uniform 0.35 --device cuda --current_fold 2 --n_splits 5; \
python train.py diabetes uniform 0.35 --output_path ./models/independent_cv/diabetes_l1_3 --model_name stump_ensemble.pkl --current_fold 3 --n_splits 5; \
python certify.py diabetes ./models/independent_cv/diabetes_l1_3/stump_ensemble.pkl ./experiments/independent_cv//diabetes_l1_3 certified_radii uniform 0.35 --device cuda --current_fold 3 --n_splits 5; \
python train.py diabetes uniform 0.35 --output_path ./models/independent_cv/diabetes_l1_4 --model_name stump_ensemble.pkl --current_fold 4 --n_splits 5; \
python certify.py diabetes ./models/independent_cv/diabetes_l1_4/stump_ensemble.pkl ./experiments/independent_cv//diabetes_l1_4 certified_radii uniform 0.35 --device cuda --current_fold 4 --n_splits 5; \
python analyze.py ./experiments/independent_cv/diabetes_l1/table 5 ./experiments/independent_cv/diabetes_l1_0/certified_radii ./experiments/independent_cv/diabetes_l1_1/certified_radii ./experiments/independent_cv/diabetes_l1_2/certified_radii ./experiments/independent_cv/diabetes_l1_3/certified_radii ./experiments/independent_cv/diabetes_l1_4/certified_radii; \
python train.py spambase uniform 4.0 --output_path ./models/independent_cv/spambase_l1_0 --model_name stump_ensemble.pkl --current_fold 0 --n_splits 5; \
python certify.py spambase ./models/independent_cv/spambase_l1_0/stump_ensemble.pkl ./experiments/independent_cv//spambase_l1_0 certified_radii uniform 4.0 --device cuda --current_fold 0 --n_splits 5; \
python train.py spambase uniform 4.0 --output_path ./models/independent_cv/spambase_l1_1 --model_name stump_ensemble.pkl --current_fold 1 --n_splits 5; \
python certify.py spambase ./models/independent_cv/spambase_l1_1/stump_ensemble.pkl ./experiments/independent_cv//spambase_l1_1 certified_radii uniform 4.0 --device cuda --current_fold 1 --n_splits 5; \
python train.py spambase uniform 4.0 --output_path ./models/independent_cv/spambase_l1_2 --model_name stump_ensemble.pkl --current_fold 2 --n_splits 5; \
python certify.py spambase ./models/independent_cv/spambase_l1_2/stump_ensemble.pkl ./experiments/independent_cv//spambase_l1_2 certified_radii uniform 4.0 --device cuda --current_fold 2 --n_splits 5; \
python train.py spambase uniform 4.0 --output_path ./models/independent_cv/spambase_l1_3 --model_name stump_ensemble.pkl --current_fold 3 --n_splits 5; \
python certify.py spambase ./models/independent_cv/spambase_l1_3/stump_ensemble.pkl ./experiments/independent_cv//spambase_l1_3 certified_radii uniform 4.0 --device cuda --current_fold 3 --n_splits 5; \
python train.py spambase uniform 4.0 --output_path ./models/independent_cv/spambase_l1_4 --model_name stump_ensemble.pkl --current_fold 4 --n_splits 5; \
python certify.py spambase ./models/independent_cv/spambase_l1_4/stump_ensemble.pkl ./experiments/independent_cv//spambase_l1_4 certified_radii uniform 4.0 --device cuda --current_fold 4 --n_splits 5; \
python analyze.py ./experiments/independent_cv/spambase_l1/table 5 ./experiments/independent_cv/spambase_l1_0/certified_radii ./experiments/independent_cv/spambase_l1_1/certified_radii ./experiments/independent_cv/spambase_l1_2/certified_radii ./experiments/independent_cv/spambase_l1_3/certified_radii ./experiments/independent_cv/spambase_l1_4/certified_radii; \
python train.py fmnist_sandal_sneaker uniform 4.0 --output_path ./models/independent_cv/fmnist_sandal_sneaker_l1_0 --model_name stump_ensemble.pkl --current_fold 0 --n_splits 5; \
python certify.py fmnist_sandal_sneaker ./models/independent_cv/fmnist_sandal_sneaker_l1_0/stump_ensemble.pkl ./experiments/independent_cv//fmnist_sandal_sneaker_l1_0 certified_radii uniform 4.0 --device cuda --current_fold 0 --n_splits 5; \
python train.py fmnist_sandal_sneaker uniform 4.0 --output_path ./models/independent_cv/fmnist_sandal_sneaker_l1_1 --model_name stump_ensemble.pkl --current_fold 1 --n_splits 5; \
python certify.py fmnist_sandal_sneaker ./models/independent_cv/fmnist_sandal_sneaker_l1_1/stump_ensemble.pkl ./experiments/independent_cv//fmnist_sandal_sneaker_l1_1 certified_radii uniform 4.0 --device cuda --current_fold 1 --n_splits 5; \
python train.py fmnist_sandal_sneaker uniform 4.0 --output_path ./models/independent_cv/fmnist_sandal_sneaker_l1_2 --model_name stump_ensemble.pkl --current_fold 2 --n_splits 5; \
python certify.py fmnist_sandal_sneaker ./models/independent_cv/fmnist_sandal_sneaker_l1_2/stump_ensemble.pkl ./experiments/independent_cv//fmnist_sandal_sneaker_l1_2 certified_radii uniform 4.0 --device cuda --current_fold 2 --n_splits 5; \
python train.py fmnist_sandal_sneaker uniform 4.0 --output_path ./models/independent_cv/fmnist_sandal_sneaker_l1_3 --model_name stump_ensemble.pkl --current_fold 3 --n_splits 5; \
python certify.py fmnist_sandal_sneaker ./models/independent_cv/fmnist_sandal_sneaker_l1_3/stump_ensemble.pkl ./experiments/independent_cv//fmnist_sandal_sneaker_l1_3 certified_radii uniform 4.0 --device cuda --current_fold 3 --n_splits 5; \
python train.py fmnist_sandal_sneaker uniform 4.0 --output_path ./models/independent_cv/fmnist_sandal_sneaker_l1_4 --model_name stump_ensemble.pkl --current_fold 4 --n_splits 5; \
python certify.py fmnist_sandal_sneaker ./models/independent_cv/fmnist_sandal_sneaker_l1_4/stump_ensemble.pkl ./experiments/independent_cv//fmnist_sandal_sneaker_l1_4 certified_radii uniform 4.0 --device cuda --current_fold 4 --n_splits 5; \
python analyze.py ./experiments/independent_cv/fmnist_sandal_sneaker_l1/table 5 ./experiments/independent_cv/fmnist_sandal_sneaker_l1_0/certified_radii ./experiments/independent_cv/fmnist_sandal_sneaker_l1_1/certified_radii ./experiments/independent_cv/fmnist_sandal_sneaker_l1_2/certified_radii ./experiments/independent_cv/fmnist_sandal_sneaker_l1_3/certified_radii ./experiments/independent_cv/fmnist_sandal_sneaker_l1_4/certified_radii; \
python train.py mnist_1_5 uniform 4.0 --output_path ./models/independent_cv/mnist_1_5_l1_0 --model_name stump_ensemble.pkl --current_fold 0 --n_splits 5; \
python certify.py mnist_1_5 ./models/independent_cv/mnist_1_5_l1_0/stump_ensemble.pkl ./experiments/independent_cv//mnist_1_5_l1_0 certified_radii uniform 4.0 --device cuda --current_fold 0 --n_splits 5; \
python train.py mnist_1_5 uniform 4.0 --output_path ./models/independent_cv/mnist_1_5_l1_1 --model_name stump_ensemble.pkl --current_fold 1 --n_splits 5; \
python certify.py mnist_1_5 ./models/independent_cv/mnist_1_5_l1_1/stump_ensemble.pkl ./experiments/independent_cv//mnist_1_5_l1_1 certified_radii uniform 4.0 --device cuda --current_fold 1 --n_splits 5; \
python train.py mnist_1_5 uniform 4.0 --output_path ./models/independent_cv/mnist_1_5_l1_2 --model_name stump_ensemble.pkl --current_fold 2 --n_splits 5; \
python certify.py mnist_1_5 ./models/independent_cv/mnist_1_5_l1_2/stump_ensemble.pkl ./experiments/independent_cv//mnist_1_5_l1_2 certified_radii uniform 4.0 --device cuda --current_fold 2 --n_splits 5; \
python train.py mnist_1_5 uniform 4.0 --output_path ./models/independent_cv/mnist_1_5_l1_3 --model_name stump_ensemble.pkl --current_fold 3 --n_splits 5; \
python certify.py mnist_1_5 ./models/independent_cv/mnist_1_5_l1_3/stump_ensemble.pkl ./experiments/independent_cv//mnist_1_5_l1_3 certified_radii uniform 4.0 --device cuda --current_fold 3 --n_splits 5; \
python train.py mnist_1_5 uniform 4.0 --output_path ./models/independent_cv/mnist_1_5_l1_4 --model_name stump_ensemble.pkl --current_fold 4 --n_splits 5; \
python certify.py mnist_1_5 ./models/independent_cv/mnist_1_5_l1_4/stump_ensemble.pkl ./experiments/independent_cv//mnist_1_5_l1_4 certified_radii uniform 4.0 --device cuda --current_fold 4 --n_splits 5; \
python analyze.py ./experiments/independent_cv/mnist_1_5_l1/table 5 ./experiments/independent_cv/mnist_1_5_l1_0/certified_radii ./experiments/independent_cv/mnist_1_5_l1_1/certified_radii ./experiments/independent_cv/mnist_1_5_l1_2/certified_radii ./experiments/independent_cv/mnist_1_5_l1_3/certified_radii ./experiments/independent_cv/mnist_1_5_l1_4/certified_radii; \
python train.py mnist_2_6 uniform 4.0 --output_path ./models/independent_cv/mnist_2_6_l1_0 --model_name stump_ensemble.pkl --current_fold 0 --n_splits 5; \
python certify.py mnist_2_6 ./models/independent_cv/mnist_2_6_l1_0/stump_ensemble.pkl ./experiments/independent_cv//mnist_2_6_l1_0 certified_radii uniform 4.0 --device cuda --current_fold 0 --n_splits 5; \
python train.py mnist_2_6 uniform 4.0 --output_path ./models/independent_cv/mnist_2_6_l1_1 --model_name stump_ensemble.pkl --current_fold 1 --n_splits 5; \
python certify.py mnist_2_6 ./models/independent_cv/mnist_2_6_l1_1/stump_ensemble.pkl ./experiments/independent_cv//mnist_2_6_l1_1 certified_radii uniform 4.0 --device cuda --current_fold 1 --n_splits 5; \
python train.py mnist_2_6 uniform 4.0 --output_path ./models/independent_cv/mnist_2_6_l1_2 --model_name stump_ensemble.pkl --current_fold 2 --n_splits 5; \
python certify.py mnist_2_6 ./models/independent_cv/mnist_2_6_l1_2/stump_ensemble.pkl ./experiments/independent_cv//mnist_2_6_l1_2 certified_radii uniform 4.0 --device cuda --current_fold 2 --n_splits 5; \
python train.py mnist_2_6 uniform 4.0 --output_path ./models/independent_cv/mnist_2_6_l1_3 --model_name stump_ensemble.pkl --current_fold 3 --n_splits 5; \
python certify.py mnist_2_6 ./models/independent_cv/mnist_2_6_l1_3/stump_ensemble.pkl ./experiments/independent_cv//mnist_2_6_l1_3 certified_radii uniform 4.0 --device cuda --current_fold 3 --n_splits 5; \
python train.py mnist_2_6 uniform 4.0 --output_path ./models/independent_cv/mnist_2_6_l1_4 --model_name stump_ensemble.pkl --current_fold 4 --n_splits 5; \
python certify.py mnist_2_6 ./models/independent_cv/mnist_2_6_l1_4/stump_ensemble.pkl ./experiments/independent_cv//mnist_2_6_l1_4 certified_radii uniform 4.0 --device cuda --current_fold 4 --n_splits 5; \
python analyze.py ./experiments/independent_cv/mnist_2_6_l1/table 5 ./experiments/independent_cv/mnist_2_6_l1_0/certified_radii ./experiments/independent_cv/mnist_2_6_l1_1/certified_radii ./experiments/independent_cv/mnist_2_6_l1_2/certified_radii ./experiments/independent_cv/mnist_2_6_l1_3/certified_radii ./experiments/independent_cv/mnist_2_6_l1_4/certified_radii; \
